#!/bin/bash

SCRIPT_VERSION="2.3.4"
UPDATE_AVAILABLE=false
DIR_REMNAWAVE="/usr/local/remnawave_reverse/"
LANG_FILE="${DIR_REMNAWAVE}selected_language"
SCRIPT_URL="https://raw.githubusercontent.com/eGamesAPI/remnawave-reverse-proxy/refs/heads/main/install_remnawave.sh"

COLOR_RESET="\033[0m"
COLOR_GREEN="\033[1;32m"
COLOR_YELLOW="\033[1;33m"
COLOR_WHITE="\033[1;37m"
COLOR_RED="\033[1;31m"
COLOR_GRAY='\033[0;90m'

# --- ФУНКЦИИ ЯЗЫКА И ИНТЕРФЕЙСА ---

load_language() {
    if [ -f "$LANG_FILE" ]; then
        local saved_lang=$(cat "$LANG_FILE")
        case $saved_lang in
            1) set_language en ;;
            2) set_language ru ;;
            *)
                rm -f "$LANG_FILE"
                return 1 ;;
        esac
        return 0
    fi
    return 1
}

declare -A LANG=(
    [CHOOSE_LANG]="Select language:"
    [LANG_EN]="English"
    [LANG_RU]="Русский"
)

show_language() {
    echo -e "${COLOR_GREEN}${LANG[CHOOSE_LANG]}${COLOR_RESET}"
    echo -e ""
    echo -e "${COLOR_YELLOW}1. ${LANG[LANG_EN]}${COLOR_RESET}"
    echo -e "${COLOR_YELLOW}2. ${LANG[LANG_RU]}${COLOR_RESET}"
    echo -e ""
}

set_language() {
    case $1 in
        en)
            LANG=(
                [ALIAS_ADDED]="Alias 'rr' for 'remnawave_reverse' added to %s"
                [ALIAS_ACTIVATE_GLOBAL]="Alias 'rr' is now available for all users. Run 'source %s' or open a new terminal to apply."
                [CHOOSE_LANG]="Select language:"
                [LANG_EN]="English"
                [LANG_RU]="Русский"
                [ERROR_ROOT]="Script must be run as root"
                [ERROR_OS]="Supported only Debian 11/12 and Ubuntu 22.04/24.04"
                [ERROR_UPDATE_LIST]="Failed to update package list"
                [ERROR_INSTALL_PACKAGES]="Failed to install required packages"
                [ERROR_INSTALL_CRON]="Failed to install cron"
                [ERROR_START_CRON]="Failed to start cron"
                [ERROR_CONFIGURE_LOCALES]="Error: Failed to configure locales"
                [ERROR_DOWNLOAD_DOCKER_KEY]="Failed to download Docker GPG key"
                [ERROR_UPDATE_DOCKER_LIST]="Failed to update package list after adding Docker repository"
                [ERROR_INSTALL_DOCKER]="Failed to install Docker"
                [ERROR_DOCKER_NOT_INSTALLED]="Docker is not installed"
                [ERROR_START_DOCKER]="Failed to start Docker"
                [ERROR_ENABLE_DOCKER]="Failed to enable Docker auto-start"
                [ERROR_DOCKER_NOT_WORKING]="Docker is not working properly"
                [ERROR_CONFIGURE_UFW]="Failed to configure UFW"
                [ERROR_CONFIGURE_UPGRADES]="Failed to configure unattended-upgrades"
                [ERROR_DOCKER_DNS]="Error: Unable to resolve download.docker.com. Check your DNS settings."
                [ERROR_INSTALL_CERTBOT]="Error: Failed to install certbot"
                [SUCCESS_INSTALL]="All packages installed successfully"
                [MENU_TITLE]="REMNAWAVE REVERSE-PROXY by eGames"
                [AVAILABLE_UPDATE]="update available"
                [VERSION_LABEL]="Version: %s"
                [EXIT]="Exit"
                [MENU_1]="Install Remnawave Components"
                [MENU_2]="Reinstall panel/node"
                [MENU_3]="Manage Panel/Node"
                [MENU_4]="Install random template for selfsteal node"
                [MENU_5]="Custom extensions by legiz"
                [MENU_6]="Extensions by distillium"
                [MENU_7]="Manage IPv6"
                [MENU_8]="Manage certificates domain"
                [MENU_9]="Check for updates script"
                [MENU_10]="Remove script"
                [PROMPT_ACTION]="Select action (0-10):"
                [INVALID_CHOICE]="Invalid choice. Please select 0-10"
                [WARNING_LABEL]="WARNING:"
                [CONFIRM_PROMPT]="Enter 'y' to continue or 'n' to exit (y/n):"
                [WARNING_NODE_PANEL]="Adding a node should only be done on the server where the panel is installed, not on the node server."
                [CONFIRM_SERVER_PANEL]="Are you sure you are on the server with the installed panel?"
                [REMOVE_SCRIPT_ONLY]="Remove script and its local files"
                [REMOVE_SCRIPT_AND_PANEL]="Remove script and remnawave panel/node data"
                [CONFIRM_REMOVE_SCRIPT]="All script data will be removed from the server. Are you sure? (y/n): "
                [CONFIRM_REMOVE_ALL]="All script and panel/node data will be removed from the server. Are you sure? (y/n): "
                [SCRIPT_REMOVED]="Script and its local files successfully removed!"
                [ALL_REMOVED]="Script and panel/node data successfully removed!"
                [EXTENSIONS_MENU]="Extensions by distillium"
                [EXTENSIONS_MENU_TITLE]="Manage Extensions by distillium"
                [EXTENSIONS_PROMPT]="Select action (0-2):"
                [EXTENSIONS_INVALID_CHOICE]="Invalid choice. Please select 0-2."
                [BACKUP_RESTORE]="Backup and Restore"
                [WARP_MENU]="WARP Native"
                [WARP_MENU_TITLE]="Manage WARP Native"
                [WARP_INSTALL]="Install WARP Native"
                [WARP_ADD_CONFIG]="Add WARP-configuration to node configuration"
                [WARP_DELETE_WARP_SETTINGS]="Remove WARP-configuration from node configuration"
                [WARP_CONFIRM_SERVER_PANEL]="Are you sure you are on the server with the installed panel?\nAdding WARP-configuration should only be done on the server where the panel is installed, not on the node server"
                [WARP_UNINSTALL]="Uninstall WARP Native"
                [WARP_PROMPT]="Select action (0-4):"
                [WARP_PROMPT1]="Select action:"
                [WARP_INVALID_CHOICE]="Invalid choice. Please select 0-4."
                [WARP_INVALID_CHOICE2]="Invalid choice."
                [WARP_NO_NODE]="Node Remnawave not found. First install the node."
                [WARP_SELECT_CONFIG]="Select node to add WARP-configuration?"
                [WARP_SELECT_CONFIG_DELETE]="Select node to remove WARP-configuration?"
                [WARP_NO_CONFIGS]="No configurations found."
                [WARP_UPDATE_SUCCESS]="Configuration successfully updated!"
                [WARP_UPDATE_FAIL]="Failed to update configuration."
                [WARP_WARNING]="warp-out already exists in outbounds."
                [WARP_WARNING2]="warp rule already exists in routing rules."
                [WARP_REMOVED_WARP_SETTINGS1]="Removed warp-out from outbounds"
                [WARP_NO_WARP_SETTINGS1]="warp-out not found in outbounds"
                [WARP_REMOVED_WARP_SETTINGS2]="Removed warp rule from routing rules"
                [WARP_NO_WARP_SETTINGS2]="warp rule not found in routing rules"
                [START_PANEL_NODE]="Start panel/node"
                [STOP_PANEL_NODE]="Stop panel/node"
                [UPDATE_PANEL_NODE]="Update panel/node"
                [VIEW_LOGS]="View logs"
                [PRESS_ENTER_RETURN_MENU]="Press Enter to return to the menu..."
                [REMNAWAVE_CLI]="Remnawave CLI"
                [ACCESS_PANEL]="Access panel via port 8443 (Only for panel + node)"
                [MANAGE_PANEL_NODE_PROMPT]="Select action (0-6):"
                [MANAGE_PANEL_NODE_INVALID_CHOICE]="Invalid choice. Please select 0-6."
                [CERT_UPDATE]="Update current certificates"
                [CERT_GENERATE]="Generate new certificates for another domain"
                [CERT_PROMPT1]="Select action (0-2):"
                [CERT_INVALID_CHOICE]="Invalid choice. Please select 0-2."
                [CERT_UPDATE_CHECK]="Checking certificate generation method..."
                [CERT_UPDATE_SUCCESS]="Certificates successfully updated."
                [CERT_UPDATE_FAIL]="Failed to update certificates."
                [CERT_GENERATE_PROMPT]="Enter the domain for new certificates (e.g., example.com):"
                [CERT_METHOD_UNKNOWN]="Unknown certificate generation method."
                [CERT_NOT_DUE]="Certificate for %s is not yet due for renewal."
                [INSTALL_MENU_TITLE]="Install Remnawave Components"
                [INSTALL_PANEL_NODE]="Install panel and node on one server"
                [INSTALL_PANEL]="Install only the panel"
                [INSTALL_ADD_NODE]="Add node to panel"
                [INSTALL_NODE]="Install only the node"
                [INSTALL_PROMPT]="Select action (0-3):"
                [INSTALL_INVALID_CHOICE]="Invalid choice. Please select 0-3."
                [IPV6_MENU_TITLE]="Manage IPv6"
                [IPV6_ENABLE]="Enable IPv6"
                [IPV6_DISABLE]="Disable IPv6"
                [IPV6_PROMPT]="Select action (0-2):"
                [IPV6_INVALID_CHOICE]="Invalid choice. Please select 0-2."
                [IPV6_ALREADY_ENABLED]="IPv6 already enabled"
                [IPV6_ALREADY_DISABLED]="IPv6 already disabled"
                [ENABLE_IPV6]="Enabling IPv6..."
                [IPV6_ENABLED]="IPv6 has been enabled."
                [DISABLING_IPV6]="Disabling IPv6..."
                [IPV6_DISABLED]="IPv6 has been disabled."
                [INSTALL_PACKAGES]="Installing required packages..."
                [INSTALLING]="Installing panel and node"
                [INSTALLING_PANEL]="Installing panel"
                [INSTALLING_NODE]="Installing node"
                [ENTER_PANEL_DOMAIN]="Enter panel domain (e.g. panel.example.com):"
                [ENTER_SUB_DOMAIN]="Enter subscription domain (e.g. sub.example.com):"
                [ENTER_NODE_DOMAIN]="Enter selfsteal domain for node (e.g. node.example.com):"
                [ENTER_CF_TOKEN]="Enter your Cloudflare API token or global API key:"
                [ENTER_CF_EMAIL]="Enter your Cloudflare registered email:"
                [ENTER_GCORE_TOKEN]="Enter Gcore API token:"
                [CERT_GCORE_FILE_NOT_FOUND]="Gcore credentials file not found. Please re-enter token."
                [CHECK_CERTS]="Checking certificates..."
                [CERT_FOUND]="Certificates found in /etc/letsencrypt/live/"
                [CF_VALIDATING]="Cloudflare API key and email are valid"
                [CF_INVALID]="Invalid Cloudflare API token or email after %d attempts."
                [CF_INVALID_ATTEMPT]="Invalid Cloudflare API key or email. Attempt %d of %d."
                [WAITING]="Please wait..."
                [REGISTERING_REMNAWAVE]="Registration in Remnawave"
                [CHECK_CONTAINERS]="Checking containers availability..."
                [CONTAINERS_NOT_READY_ATTEMPT]="Containers are not ready, waiting... Attempt %d of %d."
                [CONTAINERS_TIMEOUT]="Containers not ready after %d attempts.\n\nCheck logs:\n  cd /opt/remnawave && docker compose logs -f\n\nAlso check typical Docker issues:\n  https://wiki.egam.es/troubleshooting/docker-issues/"
                [REGISTRATION_SUCCESS]="Registration completed successfully!"
                [GET_PUBLIC_KEY]="Getting public key..."
                [PUBLIC_KEY_SUCCESS]="Public key successfully obtained"
                [GENERATE_KEYS]="Generating x25519 keys..."
                [GENERATE_KEYS_SUCCESS]="Keys successfully generated"
                [ERROR_NO_CONFIGS]="No config profiles found"
                [NO_DEFAULT_PROFILE]="Default-Profile not found"
                [ERROR_DELETE_PROFILE]="Failed to delete profile"
                [CREATING_CONFIG_PROFILE]="Creating config profile..."
                [CONFIG_PROFILE_CREATED]="Config profile successfully created"
                [CREATING_NODE]="Creating node"
                [NODE_CREATED]="Node successfully created"
                [CREATE_HOST]="Creating host"
                [HOST_CREATED]="Host successfully created"
                [GET_DEFAULT_SQUAD]="Getting default squad"
                [UPDATE_SQUAD]="Squad successfully updated"
                [NO_SQUADS_FOUND]="No squads found"
                [INVALID_UUID_FORMAT]="Invalid UUID format"
                [NO_VALID_SQUADS_FOUND]="No valid squads found"
                [ERROR_GET_SQUAD]="Failed to get squad"
                [INVALID_SQUAD_UUID]="Invalid squad UUID"
                [INVALID_INBOUND_UUID]="Invalid inbound UUID"
                [CHANGE_DIR_FAILED]="Failed to change to directory %s"
                [DIR_NOT_FOUND]="Directory /opt/remnawave not found"
                [PANEL_RUNNING]="Panel/node already running"
                [PANEL_RUN]="Panel/node running"
                [PANEL_STOP]="Panel/node stopped"
                [PANEL_STOPPED]="Panel/node already stopped"
                [NO_UPDATE]="No updates available for panel/node"
                [UPDATING]="Updating panel/node..."
                [UPDATE_SUCCESS1]="Panel/node successfully updated"
                [STARTING_PANEL_NODE]="Starting panel and node"
                [STARTING_PANEL]="Starting panel"
                [STARTING_NODE]="Starting node"
                [STOPPING_REMNAWAVE]="Stopping panel and node"
                [IMAGES_DETECTED]="Images detected, restarting containers..."
                [INSTALL_COMPLETE]="               INSTALLATION COMPLETE!"
                [PANEL_ACCESS]="Panel URL:"
                [ADMIN_CREDS]="To log into the panel, use the following data:"
                [USERNAME]="Username:"
                [PASSWORD]="Password:"
                [RELAUNCH_CMD]="To relaunch the manager, use the following command:"
                [RANDOM_TEMPLATE]="Installing random template for camouflage site"
                [DOWNLOAD_FAIL]="Download failed, retrying..."
                [UNPACK_ERROR]="Error unpacking archive"
                [TEMPLATE_COPY]="Template copied to /var/www/html/"
                [SELECT_TEMPLATE]="Selected template:"
                [ERROR_TOKEN]="Failed to get token."
                [ERROR_PUBLIC_KEY]="Failed to get public key."
                [ERROR_EXTRACT_PUBLIC_KEY]="Failed to extract public key from response."
                [ERROR_GENERATE_KEYS]="Failed to generate keys."
                [ERROR_EMPTY_RESPONSE_NODE]="Empty response from server when creating node."
                [ERROR_CREATE_NODE]="Failed to create node."
                [ERROR_EMPTY_RESPONSE_HOST]="Empty response from server when creating host."
                [ERROR_CREATE_HOST]="Failed to create host."
                [ERROR_EMPTY_RESPONSE_REGISTER]="Registration error - empty server response"
                [ERROR_REGISTER]="Registration error"
                [ERROR_UPDATE_SQUAD]="Failed to update squad"
                [ERROR_GET_SQUAD_LIST]="Failed to get squad list"
                [NO_SQUADS_TO_UPDATE]="No squads to update"
                [REINSTALL_WARNING]="All data panel/node will be deleted from the server. Are you sure? (y/n):"
                [REINSTALL_TYPE_TITLE]="Select reinstallation method:"
                [REINSTALL_PROMPT]="Select action (0-3):"
                [INVALID_REINSTALL_CHOICE]="Invalid choice. Please select 0-3."
                [POST_PANEL_MESSAGE]="Panel successfully installed!"
                [POST_PANEL_INSTRUCTION]="To install the node, follow these steps:\n1. Run this script on the server where the node will be installed.\n2. Select 'Install Remnawave Components', then 'Install only the node'."
                [SELFSTEAL_PROMPT]="Enter the selfsteal domain for the node (e.g. node.example.com):"
                [SELFSTEAL]="Enter the selfsteal domain for the node specified during panel installation:"
                [PANEL_IP_PROMPT]="Enter the IP address of the panel to establish a connection between the panel and the node:"
                [IP_ERROR]="Enter a valid IP address in the format X.X.X.X (e.g., 192.168.1.1)"
                [CERT_PROMPT]="Enter the certificate obtained from the panel (paste the content and press Enter twice):"
                [CERT_CONFIRM]="Are you sure the certificate is correct? (y/n):"
                [ABORT_MESSAGE]="Installation aborted by user"
                [SUCCESS_MESSAGE]="Node successfully connected"
                [NODE_CHECK]="Checking node connection for %s..."
                [NODE_ATTEMPT]="Attempt %d of %d..."
                [NODE_UNAVAILABLE]="Node is unavailable on attempt %d."
                [NODE_LAUNCHED]="Node successfully launched!"
                [NODE_NOT_CONNECTED]="Node not connected after %d attempts!"
                [CHECK_CONFIG]="Check the configuration or restart the panel."
                [ADD_NODE_TO_PANEL]="Adding node to panel"
                [ENTER_NODE_NAME]="Enter node name (e.g., Germany):"
                [USING_SAVED_TOKEN]="Using saved token..."
                [INVALID_SAVED_TOKEN]="Saved token is invalid. Requesting a new one..."
                [ENTER_PANEL_USERNAME]="Enter panel username: "
                [ENTER_PANEL_PASSWORD]="Enter panel password: "
                [TOKEN_RECEIVED_AND_SAVED]="Token successfully received and saved"
                [TOKEN_USED_SUCCESSFULLY]="Token successfully used"
                [DOMAIN_ALREADY_EXISTS]="Domain already exists"
                [TRY_ANOTHER_DOMAIN]="Please use another domain"
                [ERROR_CHECK_DOMAIN]="Error checking domain"
                [NODE_ADDED_SUCCESS]="Node successfully added!"
                [CREATE_NEW_NODE]="Creating new node for %s..."
                [CF_INVALID_NAME]="Error: The name of the configuration profile %s is already in use.\nPlease choose another name."
                [CF_INVALID_LENGTH]="Error: The name of the configuration profile should contain from 3 to 20 characters."
                [CF_INVALID_CHARS]="Error: The name of the configuration profile should contain only English letters, numbers, and hyphens."
                [CHECK_UPDATE]="Check for updates"
                [GENERATING_CERTS]="Generating certificates for %s"
                [REQUIRED_DOMAINS]="Required domains for certificates:"
                [CHECK_DOMAIN_IP_FAIL]="Failed to determine the domain or server IP address."
                [CHECK_DOMAIN_IP_FAIL_INSTRUCTION]="Ensure that the domain %s is correctly configured and points to this server (%s)."
                [CHECK_DOMAIN_CLOUDFLARE]="The domain %s points to a Cloudflare IP (%s)."
                [CHECK_DOMAIN_CLOUDFLARE_INSTRUCTION]="Cloudflare proxying is not allowed for the selfsteal domain. Disable proxying (switch to 'DNS Only')."
                [CHECK_DOMAIN_MISMATCH]="The domain %s points to IP address %s, which differs from this server's IP (%s)."
                [CHECK_DOMAIN_MISMATCH_INSTRUCTION]="For proper operation, the domain must point to the current server."
                [NO_PANEL_NODE_INSTALLED]="Panel or node is not installed. Please install panel or node first."
                [UPDATE_AVAILABLE]="A new version of the script is available: %s (current version: %s)."
                [UPDATE_CONFIRM]="Update the script? (y/n):"
                [UPDATE_CANCELLED]="Update cancelled by user."
                [UPDATE_SUCCESS]="Script successfully updated to version %s!"
                [UPDATE_FAILED]="Error downloading the new version of the script."
                [VERSION_CHECK_FAILED]="Could not determine the version of the remote script. Skipping update."
                [LATEST_VERSION]="You already have the latest version of the script (%s)."
                [RESTART_REQUIRED]="Please restart the script to apply changes."
                [LOCAL_FILE_NOT_FOUND]="Local script file not found, downloading new version..."
                [RUNNING_CLI]="Running Remnawave CLI..."
                [CLI_SUCCESS]="Remnawave CLI executed successfully!"
                [CLI_FAILED]="Failed to execute Remnawave CLI. Ensure the 'remnawave' container is running."
                [CONTAINER_NOT_RUNNING]="Container 'remnawave' is not running. Please start it first."
                [CERT_METHOD_PROMPT]="Select certificate generation method for all domains:"
                [CERT_METHOD_CF]="Cloudflare API (supports wildcard)"
                [CERT_METHOD_ACME]="ACME HTTP-01 (single domain, no wildcard)"
                [CERT_METHOD_GCORE]="Gcore DNS API (supports wildcard)"
                [ERROR_INSTALL_GCORE_PLUGIN]="Failed to install certbot-dns-gcore plugin"
                [CERT_METHOD_CHOOSE]="Select action (0-3):"
                [EMAIL_PROMPT]="Enter your email for Let's Encrypt registration:"
                [CERTS_SKIPPED]="All certificates already exist. Skipping generation."
                [ACME_METHOD]="Using ACME (Let's Encrypt) with HTTP-01 challenge (no wildcard support)..."
                [CERT_GENERATION_FAILED]="Certificate generation failed. Please check your input and DNS settings."
                [ADDING_CRON_FOR_EXISTING_CERTS]="Adding cron job for certificate renewal..."
                [CRON_ALREADY_EXISTS]="Cron job for certificate renewal already exists."
                [CERT_NOT_FOUND]="Certificate not found for domain."
                [ERROR_PARSING_CERT]="Error parsing certificate expiry date."
                [CERT_EXPIRY_SOON]="Certificates will expire soon in"
                [DAYS]="days"
                [UPDATING_CRON]="Updating cron job to match certificate expiry."
                [GENERATING_WILDCARD_CERT]="Generating wildcard certificate for"
                [WILDCARD_CERT_FOUND]="Wildcard certificate found in /etc/letsencrypt/live/"
                [FOR_DOMAIN]="for"
                [START_CRON_ERROR]="Not able to start cron. Please start it manually."
                [DOMAINS_MUST_BE_UNIQUE]="Error: All domains (panel, subscription, and node) must be unique."
                [CHOOSE_TEMPLATE_SOURCE]="Select template source:"
                [SIMPLE_WEB_TEMPLATES]="Simple web templates"
                [SNI_TEMPLATES]="Sni templates"
                [NOTHING_TEMPLATES]="Nothing Sni templates"
                [CHOOSE_TEMPLATE_OPTION]="Select action (0-3):"
                [INVALID_TEMPLATE_CHOICE]="Invalid choice. Please select 0-3."
                [PORT_8443_OPEN]="Open port 8443 for panel access"
                [PORT_8443_CLOSE]="Close port 8443 for panel access"
                [PORT_8443_IN_USE]="Port 8443 already in use by another process. Check which services are using the port and free it."
                [NO_PORT_CHECK_TOOLS]="Port checking tools (ss or netstat) not found. Install one of them."
                [OPEN_PANEL_LINK]="Your panel access link:"
                [PORT_8443_WARNING]="Don't forget, port 8443 is now open to the world. After fixing the panel, select the option to close port 8443."
                [PORT_8443_CLOSED]="Port 8443 has been closed."
                [NGINX_CONF_NOT_FOUND]="File nginx.conf not found in $dir"
                [NGINX_CONF_ERROR]="Failed to extract necessary parameters from nginx.conf"
                [NGINX_CONF_MODIFY_FAILED]="Failed to modify nginx.conf"
                [PORT_8443_ALREADY_CONFIGURED]="Port 8443 already configured in nginx.conf"
                [UFW_RELOAD_FAILED]="Failed to reload UFW."
                [PORT_8443_ALREADY_CLOSED]="Port 8443 already closed in UFW."
                [LEGIZ_EXTENSIONS_PROMPT]="Select action (0-2):"
                [UPLOADING_SUB_PAGE]="Uploading custom sub page template..."
                [ERROR_FETCH_SUB_PAGE]="Failed to fetch custom sub page template."
                [SUB_PAGE_UPDATED_SUCCESS]="Custom sub page template successfully updated."
                [SELECT_SUB_PAGE_CUSTOM]="Select action (0-2):"
                [SELECT_SUB_PAGE_CUSTOM1]="Custom Sub Page Templates"
                [SELECT_SUB_PAGE_CUSTOM2]="Custom Sub Page Templates\nOnly run on panel server"
                [SELECT_SUB_PAGE_CUSTOM3]="Custom App Lists for original sub page:"
                [SELECT_SUB_PAGE_CUSTOM4]="Custom Sub Page:"
                [SUB_PAGE_SELECT_CHOICE]="Invalid choice. Please select 0-2."
                [RESTORE_SUB_PAGE]="Restore default sub page"
                [CONTAINER_NOT_FOUND]="Container %s not found"
                [SUB_WITH_APPCONFIG_ASK]="Do you want to include app-config.json?"
                [SUB_WITH_APPCONFIG_OPTION1]="Yes, use config from option 1 (Simple custom app list)"
                [SUB_WITH_APPCONFIG_OPTION2]="Yes, use config from option 2 (Multiapp custom app list)"
                [SUB_WITH_APPCONFIG_OPTION3]="Yes, use config from option 3 (HWID only app list)"
                [SUB_WITH_APPCONFIG_SKIP]="No, skip app-config.json"
                [SUB_WITH_APPCONFIG_INVALID]="Invalid option, skipping app-config.json"
                [SUB_WITH_APPCONFIG_INPUT]="Select action (0-3):"
                [BRANDING_SUPPORT_ASK]="Add branding support to subscription page?"
                [BRANDING_SUPPORT_YES]="Yes, add branding support"
                [BRANDING_SUPPORT_NO]="No, skip branding"
                [BRANDING_NAME_PROMPT]="Enter your brand name:"
                [BRANDING_SUPPORT_URL_PROMPT]="Enter your support page URL:"
                [BRANDING_LOGO_URL_PROMPT]="Enter your brand logo URL:"
                [BRANDING_ADDED_SUCCESS]="Branding configuration successfully added"
                [CUSTOM_APP_LIST_MENU]="Edit custom application list and branding"
                [CUSTOM_APP_LIST_PANEL_MESSAGE]="Editing custom application list and branding is now done on the panel side"
                [CUSTOM_APP_LIST_NOT_FOUND]="Custom application list not found"
                [EDIT_BRANDING]="Edit branding"
                [EDIT_LOGO]="Change logo"
                [EDIT_NAME]="Change name in branding"
                [EDIT_SUPPORT_URL]="Change support link"
                [DELETE_APPS]="Delete specific applications"
                [BRANDING_CURRENT_VALUES]="Current branding values:"
                [BRANDING_LOGO_URL]="Logo URL:"
                [BRANDING_NAME]="Name:"
                [BRANDING_SUPPORT_URL]="Support URL:"
                [ENTER_NEW_LOGO]="Enter new logo URL:"
                [ENTER_NEW_NAME]="Enter new brand name:"
                [ENTER_NEW_SUPPORT]="Enter new support URL:"
                [CONFIRM_CHANGE]="Confirm change? (y/n):"
                [PLATFORM_SELECT]="Select platform:"
                [APP_SELECT]="Which application do you want to delete?"
                [CONFIRM_DELETE_APP]="Are you sure you want to delete application %s from platform %s? (y/n):"
                [APP_DELETED_SUCCESS]="Application successfully deleted"
                [NO_APPS_FOUND]="No applications found in this platform"
                [RENEWAL_CONF_NOT_FOUND]="Renewal configuration file not found."
                [ARCHIVE_DIR_MISMATCH]="Archive directory mismatch in configuration."
                [CERT_VERSION_NOT_FOUND]="Failed to determine certificate version."
                [RESULTS_CERTIFICATE_UPDATES]="Results of certificate updates:"
                [CERTIFICATE_FOR]="Certificate for "
                [SUCCESSFULLY_UPDATED]="successfully updated"
                [FAILED_TO_UPDATE_CERTIFICATE_FOR]="Failed to update certificate for "
                [ERROR_CHECKING_EXPIRY_FOR]="Error checking expiry date for "
                [DOES_NOT_REQUIRE_UPDATE]="does not require updating ("
                [UPDATED]="Updated"
                [REMAINING]="Remaining"
                [ERROR_UPDATE]="Error updating"
                [ALREADY_EXPIRED]="already expired"
                [CERT_CLOUDFLARE_FILE_NOT_FOUND]="Cloudflare credentials file not found."
                [TELEGRAM_OAUTH_WARNING]="Telegram OAuth is enabled (TELEGRAM_OAUTH_ENABLED=true)."
                [CREATE_API_TOKEN_INSTRUCTION]="Go to the panel at: https://%s\nNavigate to 'API Tokens' -> 'Create New Token' and create a token.\nCopy the created token and enter it below."
                [ENTER_API_TOKEN]="Enter the API token: "
                [EMPTY_TOKEN_ERROR]="No token provided. Exiting."
                [RATE_LIMIT_EXCEEDED]="Rate limit exceeded for Let's Encrypt"
                [FAILED_TO_MODIFY_HTML_FILES]="Failed to modify HTML files"
                [INSTALLING_YQ]="Installing yq..."
                [ERROR_SETTING_YQ_PERMISSIONS]="Error setting yq permissions!"
                [YQ_SUCCESSFULLY_INSTALLED]="yq successfully installed!"
                [YQ_DOESNT_WORK_AFTER_INSTALLATION]="Error: yq doesn't work after installation!"
                [ERROR_DOWNLOADING_YQ]="Error downloading yq!"
                [FAST_START]="Quick start: remnawave_reverse"
                [CREATING_API_TOKEN]="Creating API token for Subscription Page..."
                [API_TOKEN_ADDED]="API token Subscription Page successfully added to docker-compose.yml"
                [ERROR_CREATE_API_TOKEN]="Error creating API token"
                [ERROR_API_TOKEN]="Failed to add API token"
                [STOPPING_REMNAWAVE_SUBSCRIPTION_PAGE]="Stopping Remnawave Subscription Page..."
                [STARTING_REMNAWAVE_SUBSCRIPTION_PAGE]="Starting Remnawave Subscription Page..."
                [DOWNLOAD_FALLBACK]="Trying fallback download method..."
                [WARP_DELETE_SUCCESS]="WARP deleted successfully"
                [UPDATING_SQUAD]="Updating squad"
                [PORT_8443_NOT_CONFIGURED]="Port 8443 is not configured in docker-compose.yml"
                [ARCHIVE_NOT_FOUND]="Archive directory not found"
                [FILE_NOT_FOUND]="File not found:"
                [UPDATED_RENEW_AUTH]="Updated certificate renewal hook"
                [ERROR_CREATE_CONFIG_PROFILE]="Error creating config profile"
                [ERROR_EXTRACT_PRIVATE_KEY]="Failed to extract private key"
                [INVALID_CERT_METHOD]="Invalid certificate method"
            )
            ;;
        ru)
            LANG=(
                [ALIAS_ADDED]="Алиас 'rr' для 'remnawave_reverse' добавлен в %s"
                [ALIAS_ACTIVATE_GLOBAL]="Алиас 'rr' теперь доступен для всех пользователей. Выполните 'source %s' или перезапустите терминал, чтобы применить алиас."
                [ERROR_ROOT]="Скрипт нужно запускать с правами root"
                [ERROR_OS]="Поддержка только Debian 11/12 и Ubuntu 22.04/24.04"
                [MENU_TITLE]="REMNAWAVE REVERSE-PROXY by eGames"
                [AVAILABLE_UPDATE]="доступно обновление"
                [VERSION_LABEL]="Версия: %s"
                [ERROR_UPDATE_LIST]="Ошибка: Не удалось обновить список пакетов"
                [ERROR_INSTALL_PACKAGES]="Ошибка: Не удалось установить необходимые пакеты"
                [ERROR_INSTALL_CRON]="Ошибка: Не удалось установить cron"
                [ERROR_START_CRON]="Ошибка: Не удалось запустить cron"
                [ERROR_CONFIGURE_LOCALES]="Ошибка: Не удалось настроить локали"
                [ERROR_DOWNLOAD_DOCKER_KEY]="Ошибка: Не удалось загрузить ключ Docker"
                [ERROR_UPDATE_DOCKER_LIST]="Ошибка: Не удалось обновить список пакетов после добавления репозитория Docker"
                [ERROR_INSTALL_DOCKER]="Ошибка: Не удалось установить Docker"
                [ERROR_DOCKER_NOT_INSTALLED]="Ошибка: Docker не установлен"
                [ERROR_START_DOCKER]="Ошибка: Не удалось запустить Docker"
                [ERROR_ENABLE_DOCKER]="Ошибка: Не удалось включить автозапуск Docker"
                [ERROR_DOCKER_NOT_WORKING]="Ошибка: Docker не работает корректно"
                [ERROR_CONFIGURE_UFW]="Ошибка: Не удалось настроить UFW"
                [ERROR_CONFIGURE_UPGRADES]="Ошибка: Не удалось настроить unattended-upgrades"
                [ERROR_DOCKER_DNS]="Ошибка: Не удалось разрешить домен download.docker.com. Проверьте настройки DNS."
                [ERROR_INSTALL_CERTBOT]="Ошибка: Не удалось установить certbot"
                [SUCCESS_INSTALL]="Все пакеты успешно установлены"
                [EXIT]="Выход"
                [MENU_1]="Установка компонентов Remnawave"
                [MENU_2]="Переустановить панель/ноду"
                [MENU_3]="Управление панелью/нодой"
                [MENU_4]="Установить случайный шаблон для selfsteal ноды"
                [MENU_5]="Кастомные расширения от legiz"
                [MENU_6]="Управление расширениями от distillium"
                [MENU_7]="Управление IPv6"
                [MENU_8]="Управление сертификатами домена"
                [MENU_9]="Проверить обновления скрипта"
                [MENU_10]="Удалить скрипт"
                [PROMPT_ACTION]="Выберите действие (0-10):"
                [INVALID_CHOICE]="Неверный выбор. Выберите 0-10."
                [WARNING_LABEL]="ВНИМАНИЕ:"
                [CONFIRM_PROMPT]="Введите 'y' для продолжения или 'n' для выхода (y/n):"
                [WARNING_NODE_PANEL]="Добавление ноды должно выполняться только на сервере, где установлена панель, а не на сервере ноды."
                [CONFIRM_SERVER_PANEL]="Вы уверены, что находитесь на сервере с установленной панелью?"
                [REMOVE_SCRIPT_ONLY]="Удалить скрипт и его локальные файлы"
                [REMOVE_SCRIPT_AND_PANEL]="Удалить скрипт и данные панели/ноды remnawave"
                [CONFIRM_REMOVE_SCRIPT]="Все данные скрипта будут удалены с сервера. Вы уверены? (y/n): "
                [CONFIRM_REMOVE_ALL]="Все данные скрипта и панели/ноды будут удалены с сервера. Вы уверены? (y/n): "
                [SCRIPT_REMOVED]="Скрипт и его локальные файлы успешно удалены!"
                [ALL_REMOVED]="Скрипт и данные панели/ноды успешно удалены!"
                [EXTENSIONS_MENU]="Расширения by distillium"
                [EXTENSIONS_MENU_TITLE]="Управление расширениями"
                [EXTENSIONS_PROMPT]="Выберите действие (0-2):"
                [EXTENSIONS_INVALID_CHOICE]="Неверный выбор. Выберите 0-2."
                [BACKUP_RESTORE]="Backup and Restore"
                [WARP_MENU]="WARP Native"
                [WARP_MENU_TITLE]="Управление WARP Native"
                [WARP_INSTALL]="Установить WARP Native"
                [WARP_ADD_CONFIG]="Добавить WARP-настройки в конфигурацию ноды"
                [WARP_DELETE_WARP_SETTINGS]="Удалить WARP-настройки из конфигурации ноды"
                [WARP_CONFIRM_SERVER_PANEL]="Вы уверены, что находитесь на сервере с установленной панелью?\nДобавление WARP-настроек должно выполняться только на сервере, где установлена панель, а не на сервере ноды"
                [WARP_UNINSTALL]="Удалить WARP Native"
                [WARP_PROMPT]="Выберите действие (0-4):"
                [WARP_PROMPT1]="Выберите действие:"
                [WARP_INVALID_CHOICE]="Неверный выбор. Выберите 0-4."
                [WARP_INVALID_CHOICE2]="Неверный выбор."
                [WARP_NO_NODE]="Нода Remnawave не найдена. Сначала установите ноду."
                [WARP_SELECT_CONFIG]="На какую ноду добавить WARP-настройки?"
                [WARP_SELECT_CONFIG_DELETE]="На какой ноде удалить WARP-настройки?"
                [WARP_NO_CONFIGS]="Конфигурации не найдены."
                [WARP_UPDATE_SUCCESS]="Конфигурация успешно обновлена!"
                [WARP_UPDATE_FAIL]="Не удалось обновить конфигурацию."
                [WARP_WARNING]="warp-out уже существует в outbounds."
                [WARP_WARNING2]="warp rule уже существует в routing rules."
                [WARP_REMOVED_WARP_SETTINGS1]="Удален warp-out из outbounds"
                [WARP_NO_WARP_SETTINGS1]="warp-out не найден в outbounds"
                [WARP_REMOVED_WARP_SETTINGS2]="Удален warp rule из routing rules"
                [WARP_NO_WARP_SETTINGS2]="warp rule не найден в routing rules"
                [START_PANEL_NODE]="Запустить панель/ноду"
                [STOP_PANEL_NODE]="Остановить панель/ноду"
                [UPDATE_PANEL_NODE]="Обновить панель/ноду"
                [VIEW_LOGS]="Просмотр логов"
                [PRESS_ENTER_RETURN_MENU]="Нажмите Enter для возврата в меню..."
                [REMNAWAVE_CLI]="Remnawave CLI"
                [ACCESS_PANEL]="Доступ к панели через порт 8443 (только для панели + ноды)"
                [MANAGE_PANEL_NODE_PROMPT]="Выберите действие (0-6):"
                [MANAGE_PANEL_NODE_INVALID_CHOICE]="Неверный выбор. Выберите 0-6."
                [CERT_UPDATE]="Обновить текущие сертификаты"
                [CERT_GENERATE]="Сгенерировать новые сертификаты для другого домена"
                [CERT_PROMPT1]="Выберите действие (0-2):"
                [CERT_INVALID_CHOICE]="Неверный выбор. Выберите 0-2."
                [CERT_UPDATE_CHECK]="Проверка метода генерации сертификата..."
                [CERT_UPDATE_SUCCESS]="Сертификаты успешно обновлены."
                [CERT_UPDATE_FAIL]="Не удалось обновить сертификаты."
                [CERT_GENERATE_PROMPT]="Введите домен для новых сертификатов (например, example.com):"
                [CERT_METHOD_UNKNOWN]="Неизвестный метод генерации сертификата."
                [CERT_NOT_DUE]="Сертификат для %s еще не требует обновления."
                [INSTALL_MENU_TITLE]="Установка компонентов Remnawave"
                [INSTALL_PANEL_NODE]="Установить панель и ноду на один сервер"
                [INSTALL_PANEL]="Установить только панель"
                [INSTALL_ADD_NODE]="Добавить ноду в панель"
                [INSTALL_NODE]="Установить только ноду"
                [INSTALL_PROMPT]="Выберите действие (0-4):"
                [INSTALL_INVALID_CHOICE]="Неверный выбор. Выберите 0-4."
                [IPV6_MENU_TITLE]="Управление IPv6"
                [IPV6_ENABLE]="Включить IPv6"
                [IPV6_DISABLE]="Отключить IPv6"
                [IPV6_PROMPT]="Выберите действие (0-2):"
                [IPV6_INVALID_CHOICE]="Неверный выбор. Выберите 0-2."
                [IPV6_ALREADY_ENABLED]="IPv6 уже включен"
                [ENABLE_IPV6]="Включение IPv6..."
                [IPV6_ENABLED]="IPv6 включен."
                [IPV6_ALREADY_DISABLED]="IPv6 уже отключен"
                [DISABLING_IPV6]="Отключение IPv6..."
                [IPV6_DISABLED]="IPv6 отключен."
                [INSTALL_PACKAGES]="Установка необходимых пакетов..."
                [INSTALLING]="Установка панели и ноды"
                [INSTALLING_PANEL]="Установка панели"
                [INSTALLING_NODE]="Установка ноды"
                [ENTER_PANEL_DOMAIN]="Введите домен панели (например, panel.example.com):"
                [ENTER_SUB_DOMAIN]="Введите домен подписки (например, sub.example.com):"
                [ENTER_NODE_DOMAIN]="Введите selfsteal домен для ноды (например, node.example.com):"
                [ENTER_CF_TOKEN]="Введите Cloudflare API токен или глобальный ключ:"
                [ENTER_CF_EMAIL]="Введите зарегистрированную почту Cloudflare:"
                [ENTER_GCORE_TOKEN]="Введите API‑токен Gcore:"
                [CERT_GCORE_FILE_NOT_FOUND]="Файл с реквизитами Gcore не найден. Повторно введите токен."
                [ERROR_INSTALL_GCORE_PLUGIN]="Не удалось установить плагин certbot-dns-gcore"
                [CHECK_CERTS]="Проверка сертификатов..."
                [CERT_FOUND]="Сертификаты найдены в /etc/letsencrypt/live/"
                [CF_VALIDATING]="Cloudflare API ключ и email валидны"
                [CF_INVALID]="Неверный Cloudflare API ключ или email после %d попыток."
                [CF_INVALID_ATTEMPT]="Неверный Cloudflare API ключ или email. Попытка %d из %d."
                [WAITING]="Пожалуйста, подождите..."
                [REGISTERING_REMNAWAVE]="Регистрируем пользователя в панели Remnawave"
                [CHECK_CONTAINERS]="Проверка доступности контейнеров..."
                [CONTAINERS_NOT_READY_ATTEMPT]="Контейнеры не готовы, ожидание... Попытка %d из %d."
                [CONTAINERS_TIMEOUT]="Контейнеры не готовы после %d попыток.\n\nПроверьте логи:\n  cd /opt/remnawave && docker compose logs -f\n\nТакже посмотрите типичные ошибки Docker:\n  https://wiki.egam.es/ru/troubleshooting/docker-issues/"
                [REGISTRATION_SUCCESS]="Регистрация прошла успешно!"
                [GET_PUBLIC_KEY]="Получаем публичный ключ..."
                [PUBLIC_KEY_SUCCESS]="Публичный ключ успешно получен"
                [GENERATE_KEYS]="Генерация ключей x25519..."
                [GENERATE_KEYS_SUCCESS]="Ключи успешно сгенерированы"
                [CREATING_CONFIG_PROFILE]="Создаем конфигурационный профиль..."
                [CONFIG_PROFILE_CREATED]="Конфигурационный профиль успешно создан"
                [CREATING_NODE]="Создание ноды"
                [NODE_CREATED]="Нода успешно создана"
                [CREATE_HOST]="Создаем хост"
                [HOST_CREATED]="Хост успешно создан"
                [GET_DEFAULT_SQUAD]="Получение внутреннего сквада"
                [UPDATE_SQUAD]="Сквад успешно обновлен"
                [NO_SQUADS_FOUND]="Нет внутренних сквадов"
                [INVALID_UUID_FORMAT]="Неверный формат UUID"
                [NO_VALID_SQUADS_FOUND]="Нет валидных сквадов"
                [ERROR_GET_SQUAD]="Не удалось получить сквад"
                [INVALID_SQUAD_UUID]="Неверный UUID сквада"
                [INVALID_INBOUND_UUID]="Неверный UUID входа"
                [CHANGE_DIR_FAILED]="Не удалось перейти в директорию %s"
                [DIR_NOT_FOUND]="Директория /opt/remnawave не найдена"
                [PANEL_RUNNING]="Панель/нода уже запущена"
                [PANEL_RUN]="Панель/нода запущена"
                [PANEL_STOP]="Панель/нода остановлена"
                [PANEL_STOPPED]="Панель/нода уже остановлена"
                [NO_UPDATE]="Нет доступных обновлений для панели/ноды"
                [UPDATING]="Обновление панели/ноды..."
                [UPDATE_SUCCESS1]="Панель/нода успешно обновлена"
                [STARTING_PANEL_NODE]="Запуск панели и ноды"
                [STARTING_PANEL]="Запуск панели"
                [STARTING_NODE]="Запуск ноды"
                [STOPPING_REMNAWAVE]="Остановка панели и ноды"
                [IMAGES_DETECTED]="Обнаружены новые образы, перезапускаем контейнеры..."
                [INSTALL_COMPLETE]="               УСТАНОВКА ЗАВЕРШЕНА!"
                [PANEL_ACCESS]="Панель доступна по адресу:"
                [ADMIN_CREDS]="Для входа в панель используйте следующие данные:"
                [USERNAME]="Логин:"
                [PASSWORD]="Пароль:"
                [RELAUNCH_CMD]="Для повторного запуска менеджера используйте команду:"
                [DOWNLOAD_FAIL]="Ошибка загрузки, повторная попытка..."
                [UNPACK_ERROR]="Ошибка распаковки архива"
                [RANDOM_TEMPLATE]="Установка случайного шаблона для маскировочного сайта"
                [TEMPLATE_COPY]="Шаблон скопирован в /var/www/html/"
                [SELECT_TEMPLATE]="Выбран шаблон:"
                [ERROR_TOKEN]="Не удалось получить токен."
                [ERROR_PUBLIC_KEY]="Не удалось получить публичный ключ."
                [ERROR_EXTRACT_PUBLIC_KEY]="Не удалось извлечь публичный ключ из ответа."
                [ERROR_GENERATE_KEYS]="Не удалось сгенерировать ключи."
                [ERROR_NO_CONFIGS]="Не найдены профили конфигураций"
                [NO_DEFAULT_PROFILE]="Default-Profile не найден"
                [ERROR_DELETE_PROFILE]="Не удалось удалить профиль"
                [ERROR_EMPTY_RESPONSE_NODE]="Пустой ответ от сервера при создании ноды."
                [ERROR_CREATE_NODE]="Не удалось создать ноду."
                [ERROR_EMPTY_RESPONSE_HOST]="Пустой ответ от сервера при создании хоста."
                [ERROR_CREATE_HOST]="Не удалось создать хост."
                [ERROR_EMPTY_RESPONSE_REGISTER]="Ошибка при регистрации - пустой ответ сервера"
                [ERROR_REGISTER]="Ошибка регистрации"
                [ERROR_UPDATE_SQUAD]="Ошибка обновления squad"
                [ERROR_GET_SQUAD_LIST]="Ошибка получения списка squadов"
                [NO_SQUADS_TO_UPDATE]="Нет сквадов для обновления"
                [REINSTALL_WARNING]="Все данные панели/ноды будут удалены с сервера. Вы уверены? (y/n):"
                [REINSTALL_TYPE_TITLE]="Выберите способ переустановки:"
                [REINSTALL_PROMPT]="Выберите действие (0-3):"
                [INVALID_REINSTALL_CHOICE]="Неверный выбор. Выберите 0-3."
                [POST_PANEL_MESSAGE]="Панель успешно установлена!"
                [POST_PANEL_INSTRUCTION]="Для установки ноды выполните следующие шаги:\n1. Запустите этот скрипт на сервере, где будет установлена нода.\n2. Выберите 'Установка компонентов Remnawave', а затем 'Установить только ноду'."
                [SELFSTEAL]="Введите selfsteal домен для ноды, который указали при установке панели:"
                [PANEL_IP_PROMPT]="Введите IP адрес панели, чтобы установить соединение между панелью и ноды:"
                [IP_ERROR]="Введите корректный IP-адрес в формате X.X.X.X (например, 192.168.1.1)"
                [CERT_PROMPT]="Введите сертификат, полученный от панели (вставьте содержимое и 2 раза нажмите Enter):"
                [CERT_CONFIRM]="Вы уверены, что сертификат правильный? (y/n):"
                [ABORT_MESSAGE]="Установка прервана пользователем"
                [SUCCESS_MESSAGE]="Нода успешно подключена"
                [NODE_CHECK]="Проверка подключения ноды для %s..."
                [NODE_ATTEMPT]="Попытка %d из %d..."
                [NODE_UNAVAILABLE]="Нода недоступна на попытке %d."
                [NODE_LAUNCHED]="Нода успешно подключена!"
                [NODE_NOT_CONNECTED]="Нода не подключена после %d попыток!"
                [CHECK_CONFIG]="Проверьте конфигурацию или перезапустите панель."
                [ADD_NODE_TO_PANEL]="Добавить ноду в панель"
                [ENTER_NODE_NAME]="Введите имя для вашей ноды (например, Germany):"
                [USING_SAVED_TOKEN]="Используем сохранённый токен..."
                [INVALID_SAVED_TOKEN]="Сохранённый токен недействителен. Запрашиваем новый..."
                [ENTER_PANEL_USERNAME]="Введите логин панели: "
                [ENTER_PANEL_PASSWORD]="Введите пароль панели: "
                [TOKEN_RECEIVED_AND_SAVED]="Токен успешно получен и сохранён"
                [TOKEN_USED_SUCCESSFULLY]="Токен успешно использован"
                [DOMAIN_ALREADY_EXISTS]="Домен уже используется"
                [TRY_ANOTHER_DOMAIN]="Пожалуйста, используйте другой домен"
                [ERROR_CHECK_DOMAIN]="Ошибка при проверке домена"
                [NODE_ADDED_SUCCESS]="Нода успешно добавлена!"
                [CREATE_NEW_NODE]="Создаём новую ноду для %s"
                [CF_INVALID_NAME]="Ошибка: Имя конфигурационного профиля %s уже используется.\nПожалуйста, выберите другое имя."
                [CF_INVALID_LENGTH]="Ошибка: Имя конфигурационного профиля должно содержать от 3 до 20 символов."
                [CF_INVALID_CHARS]="Ошибка: Имя конфигурационного профиля должно содержать только английские буквы, цифры и дефис."
                [CHECK_UPDATE]="Проверить обновления"
                [GENERATING_CERTS]="Генерируем сертификаты для %s"
                [REQUIRED_DOMAINS]="Требуемые домены для сертификатов:"
                [CHECK_DOMAIN_IP_FAIL]="Не удалось определить IP-адрес домена или сервера."
                [CHECK_DOMAIN_IP_FAIL_INSTRUCTION]="Убедитесь, что домен %s правильно настроен и указывает на этот сервер (%s)."
                [CHECK_DOMAIN_CLOUDFLARE]="Домен %s указывает на IP Cloudflare (%s)."
                [CHECK_DOMAIN_CLOUDFLARE_INSTRUCTION]="Проксирование Cloudflare недопустимо для selfsteal домена. Отключите проксирование (переключите в режим 'DNS Only')."
                [CHECK_DOMAIN_MISMATCH]="Домен %s указывает на IP-адрес %s, который отличается от IP этого сервера (%s)."
                [CHECK_DOMAIN_MISMATCH_INSTRUCTION]="Для корректной работы домен должен указывать на текущий сервер."
                [NO_PANEL_NODE_INSTALLED]="Панель или нода не установлены. Пожалуйста, сначала установите панель или ноду."
                [UPDATE_AVAILABLE]="Доступна новая версия скрипта: %s (текущая версия: %s)."
                [UPDATE_CONFIRM]="Обновить скрипт? (y/n):"
                [UPDATE_CANCELLED]="Обновление отменено пользователем."
                [UPDATE_SUCCESS]="Скрипт успешно обновлён до версии %s!"
                [UPDATE_FAILED]="Ошибка при скачивании новой версии скрипта."
                [VERSION_CHECK_FAILED]="Не удалось определить версию удалённого скрипта. Пропускаем обновление."
                [LATEST_VERSION]="У вас уже установлена последняя версия скрипта (%s)."
                [RESTART_REQUIRED]="Пожалуйста, перезапустите скрипт для применения изменений."
                [LOCAL_FILE_NOT_FOUND]="Локальный файл скрипта не найден, загружаем новую версию..."
                [RUNNING_CLI]="Запуск Remnawave CLI..."
                [CLI_SUCCESS]="Remnawave CLI успешно выполнен!"
                [CLI_FAILED]="Не удалось выполнить Remnawave CLI. Убедитесь, что контейнер 'remnawave' запущен."
                [CONTAINER_NOT_RUNNING]="Контейнер 'remnawave' не запущен. Пожалуйста, запустите его сначала."
                [CERT_METHOD_PROMPT]="Выберите метод генерации сертификатов для всех доменов:"
                [CERT_METHOD_CF]="Cloudflare API (поддерживает wildcard)"
                [CERT_METHOD_ACME]="ACME HTTP-01 (один домен, без wildcard)"
                [CERT_METHOD_GCORE]="Gcore DNS API (поддерживает wildcard)"
                [CERT_METHOD_CHOOSE]="Выберите действие (0-3):"
                [EMAIL_PROMPT]="Введите ваш email для регистрации в Let's Encrypt:"
                [CERTS_SKIPPED]="Все сертификаты уже существуют. Пропускаем генерацию."
                [ACME_METHOD]="Используем ACME (Let's Encrypt) с HTTP-01 вызовом (без поддержки wildcard)..."
                [CERT_GENERATION_FAILED]="Не удалось сгенерировать сертификаты. Проверьте введенные данные и настройки DNS."
                [ADDING_CRON_FOR_EXISTING_CERTS]="Добавление cron-задачи для обновления сертификатов..."
                [CRON_ALREADY_EXISTS]="Задача cron для обновления сертификатов уже существует."
                [CERT_NOT_FOUND]="Сертификат для домена не найден."
                [ERROR_PARSING_CERT]="Ошибка при разборе даты истечения сертификата."
                [CERT_EXPIRY_SOON]="Сертификаты скоро истекут через"
                [DAYS]="дней"
                [UPDATING_CRON]="Обновление задачи cron в соответствии со сроком действия сертификата."
                [GENERATING_WILDCARD_CERT]="Генерация wildcard-сертификата для"
                [WILDCARD_CERT_FOUND]="Wildcard-сертификат найден в /etc/letsencrypt/live/"
                [FOR_DOMAIN]="для"
                [START_CRON_ERROR]="Не удалось запустить cron. Пожалуйста, запустите его вручную."
                [DOMAINS_MUST_BE_UNIQUE]="Ошибка: Все домены (панель, подписка, и нода) должны быть уникальными."
                [CHOOSE_TEMPLATE_SOURCE]="Выберите источник шаблонов:"
                [SIMPLE_WEB_TEMPLATES]="Simple web templates"
                [SNI_TEMPLATES]="SNI templates"
                [NOTHING_TEMPLATES]="Nothing Sni templates"
                [CHOOSE_TEMPLATE_OPTION]="Выберите действие (0-3):"
                [INVALID_TEMPLATE_CHOICE]="Неверный выбор. Выберите 0-3."
                [PORT_8443_OPEN]="Открыть доступ к панели на порту 8443"
                [PORT_8443_CLOSE]="Закрыть доступ к панели на порту 8443"
                [PORT_8443_IN_USE]="Порт 8443 уже занят другим процессом. Проверьте, какие службы используют порт, и освободите его."
                [NO_PORT_CHECK_TOOLS]="Не найдены инструменты для проверки порта (ss или netstat). Установите один из них."
                [OPEN_PANEL_LINK]="Ваша ссылка для входа в панель:"
                [PORT_8443_WARNING]="Не забудьте, что порт 8443 сейчас открыт для внешнего доступа. После восстановления панели выберите пункт закрытия порта 8443."
                [PORT_8443_CLOSED]="Порт 8443 закрыт."
                [NGINX_CONF_NOT_FOUND]="Файл nginx.conf не найден в $dir"
                [NGINX_CONF_ERROR]="Не удалось извлечь необходимые параметры из nginx.conf"
                [NGINX_CONF_MODIFY_FAILED]="Не удалось изменить конфигурацию Nginx."
                [PORT_8443_ALREADY_CONFIGURED]="Порт 8443 уже настроен в конфигурации Nginx."
                [UFW_RELOAD_FAILED]="Не удалось перезагрузить UFW."
                [PORT_8443_ALREADY_CLOSED]="Порт 8443 уже закрыт в UFW."
                [LEGIZ_EXTENSIONS_PROMPT]="Выберите действие (0-2):"
                [UPLOADING_SUB_PAGE]="Загрузка пользовательского шаблона страницы подписки..."
                [ERROR_FETCH_SUB_PAGE]="Не удалось получить пользовательский шаблон страницы подписки."
                [SUB_PAGE_UPDATED_SUCCESS]="Пользовательский шаблон страницы подписки успешно обновлён."
                [SELECT_SUB_PAGE_CUSTOM]="Выберите действие (0-2):"
                [SELECT_SUB_PAGE_CUSTOM1]="Шаблоны страниц подписки"
                [SELECT_SUB_PAGE_CUSTOM2]="Шаблоны страниц подписки\nЗапускать только на сервере с панелью"
                [SELECT_SUB_PAGE_CUSTOM3]="Списки приложений для оригинальной страницы подписки:"
                [SELECT_SUB_PAGE_CUSTOM4]="Кастомные страницы подписки:"
                [SUB_PAGE_SELECT_CHOICE]="Недопустимый выбор. Пожалуйста, выберите от 0 до 2."
                [RESTORE_SUB_PAGE]="Восстановить шаблон страницы подписки по умолчанию"
                [CONTAINER_NOT_FOUND]="Контейнер %s не найден"
                [SUB_WITH_APPCONFIG_ASK]="Добавить файл конфигурации app-config.json?"
                [SUB_WITH_APPCONFIG_OPTION1]="Простой список приложений clash&sing"
                [SUB_WITH_APPCONFIG_OPTION2]="Множественный список приложений"
                [SUB_WITH_APPCONFIG_OPTION3]="Список приложений с поддержкой HWID"
                [SUB_WITH_APPCONFIG_SKIP]="Нет, пропустить добавление конфигурации"
                [SUB_WITH_APPCONFIG_INVALID]="Неверный выбор, конфигурация не будет добавлена"
                [SUB_WITH_APPCONFIG_INPUT]="Выберите действие (0–3):"
                [BRANDING_SUPPORT_ASK]="Добавить поддержку брендирования страницы подписки?"
                [BRANDING_SUPPORT_YES]="Да, добавить поддержку брендирования"
                [BRANDING_SUPPORT_NO]="Нет, пропустить брендирование"
                [BRANDING_NAME_PROMPT]="Введите название вашего бренда:"
                [BRANDING_SUPPORT_URL_PROMPT]="Введите ссылку на страницу поддержки:"
                [BRANDING_LOGO_URL_PROMPT]="Введите ссылку на логотип вашего бренда:"
                [BRANDING_ADDED_SUCCESS]="Конфигурация брендирования успешно добавлена"
                [CUSTOM_APP_LIST_MENU]="Редактирование кастомного списка приложений и брендирования"
                [CUSTOM_APP_LIST_PANEL_MESSAGE]="Редактирование кастомного списка приложений и брендирования теперь осуществляется на стороне панели"
                [CUSTOM_APP_LIST_NOT_FOUND]="Кастомный список приложений не найден"
                [EDIT_BRANDING]="Редактирование брендирования"
                [EDIT_LOGO]="Изменить логотип"
                [EDIT_NAME]="Изменить имя в брендировании"
                [EDIT_SUPPORT_URL]="Изменить ссылку поддержки"
                [DELETE_APPS]="Удалить определенные приложения"
                [BRANDING_CURRENT_VALUES]="Текущие значения брендирования:"
                [BRANDING_LOGO_URL]="URL логотипа:"
                [BRANDING_NAME]="Имя:"
                [BRANDING_SUPPORT_URL]="URL поддержки:"
                [ENTER_NEW_LOGO]="Введите новый URL логотипа:"
                [ENTER_NEW_NAME]="Введите новое имя бренда:"
                [ENTER_NEW_SUPPORT]="Введите новую ссылку поддержки:"
                [CONFIRM_CHANGE]="Подтвердить изменение? (y/n):"
                [PLATFORM_SELECT]="Выберите платформу:"
                [APP_SELECT]="Какое приложение вы хотите удалить?"
                [CONFIRM_DELETE_APP]="Вы точно хотите удалить приложение %s из списка платформы %s? (y/n):"
                [APP_DELETED_SUCCESS]="Приложение успешно удалено"
                [NO_APPS_FOUND]="Приложения не найдены в этой платформе"
                [RENEWAL_CONF_NOT_FOUND]="Файл конфигурации обновления сертификатов не найден."
                [ARCHIVE_DIR_MISMATCH]="Несоответствие директории архива в конфигурации."
                [CERT_VERSION_NOT_FOUND]="Не удалось определить версию сертификатов."
                [RESULTS_CERTIFICATE_UPDATES]="Результаты обновления сертификатов:"
                [CERTIFICATE_FOR]="Сертификат для "
                [SUCCESSFULLY_UPDATED]="успешно обновлен"
                [FAILED_TO_UPDATE_CERTIFICATE_FOR]="Не удалось обновить сертификат для "
                [ERROR_CHECKING_EXPIRY_FOR]="Ошибка проверки даты истечения для "
                [DOES_NOT_REQUIRE_UPDATE]="не требует обновления ("
                [UPDATED]="Обновлен"
                [REMAINING]="Осталось"
                [ERROR_UPDATE]="Ошибка обновления"
                [ALREADY_EXPIRED]="уже истек"
                [CERT_CLOUDFLARE_FILE_NOT_FOUND]="Файл учетных данных Cloudflare не найден."
                [TELEGRAM_OAUTH_WARNING]="Включена авторизация через Telegram (TELEGRAM_OAUTH_ENABLED=true)."
                [CREATE_API_TOKEN_INSTRUCTION]="Зайдите в панель по адресу: https://%s\nПерейдите в раздел 'API токены' -> 'Создать новый токен' и создайте токен.\nСкопируйте созданный токен и введите его ниже."
                [ENTER_API_TOKEN]="Введите API-токен: "
                [EMPTY_TOKEN_ERROR]="Токен не введен. Завершение работы."
                [RATE_LIMIT_EXCEEDED]="Превышен лимит выдачи сертификатов Let's Encrypt"
                [FAILED_TO_MODIFY_HTML_FILES]="Не удалось изменить HTML файлы"
                [INSTALLING_YQ]="Установка yq..."
                [ERROR_SETTING_YQ_PERMISSIONS]="Ошибка установки прав yq!"
                [YQ_SUCCESSFULLY_INSTALLED]="yq успешно установлен!"
                [YQ_DOESNT_WORK_AFTER_INSTALLATION]="Ошибка: yq не работает после установки!"
                [ERROR_DOWNLOADING_YQ]="Ошибка загрузки yq!"
                [FAST_START]="Быстрый запуск: remnawave_reverse"
                [CREATING_API_TOKEN]="Создание API токена для Subscription Page..."
                [API_TOKEN_ADDED]="API токен Subscription Page успешно добавлен в docker-compose.yml"
                [ERROR_CREATE_API_TOKEN]="Ошибка создания API токена"
                [ERROR_API_TOKEN]="Не удалось добавить API токен"
                [STOPPING_REMNAWAVE_SUBSCRIPTION_PAGE]="Остановка Remnawave Subscription Page..."
                [STARTING_REMNAWAVE_SUBSCRIPTION_PAGE]="Запуск Remnawave Subscription Page..."
                [DOWNLOAD_FALLBACK]="Попытка резервного метода загрузки..."
                [WARP_DELETE_SUCCESS]="WARP успешно удалён"
                [UPDATING_SQUAD]="Обновление squad"
                [PORT_8443_NOT_CONFIGURED]="Порт 8443 не настроен в docker-compose.yml"
                [ARCHIVE_NOT_FOUND]="Директория archive не найдена"
                [FILE_NOT_FOUND]="Файл не найден:"
                [UPDATED_RENEW_AUTH]="Обновлён hook обновления сертификата"
                [ERROR_CREATE_CONFIG_PROFILE]="Ошибка создания профиля конфигурации"
                [ERROR_EXTRACT_PRIVATE_KEY]="Не удалось извлечь приватный ключ"
                [INVALID_CERT_METHOD]="Неверный метод получения сертификата"
            )
            ;;
    esac
}

# --- ВСПОМОГАТЕЛЬНЫЕ ФУНКЦИИ ---

question() { echo -e "${COLOR_GREEN}[?]${COLOR_RESET} ${COLOR_YELLOW}$*${COLOR_RESET}"; }
reading() { read -rp " $(question "$1")" "$2"; }
error() { echo -e "${COLOR_RED}$*${COLOR_RESET}"; exit 1; }

# [Здесь должны быть все ваши функции: check_os, check_root, start_panel_node, installation и т.д.]
# В целях краткости я предполагаю, что они уже есть в вашем файле выше.

# --- ОСНОВНОЙ ЦИКЛ МЕНЮ ---

main_menu() {
    clear
    check_update_status
    show_menu

    reading "${LANG[PROMPT_ACTION]}" OPTION

    case $OPTION in
        1) manage_install ;;
        2) choose_reinstall_type ;;
        3) show_panel_node_menu ;;
        4)
            if [ ! -d "/opt/remnawave" ]; then
                echo -e "${COLOR_YELLOW}${LANG[NO_PANEL_NODE_INSTALLED]}${COLOR_RESET}"
                sleep 2
            else
                show_template_source_options
                reading "${LANG[CHOOSE_TEMPLATE_OPTION]}" TEMPLATE_OPTION
                case $TEMPLATE_OPTION in
                    1) randomhtml "simple" ;;
                    2) randomhtml "sni" ;;
                    3) randomhtml "nothing" ;;
                    0) ;;
                    *) echo -e "${COLOR_YELLOW}${LANG[INVALID_TEMPLATE_CHOICE]}${COLOR_RESET}"; sleep 1 ;;
                esac
            fi
            ;;
        5) manage_custom_legiz ;;
        6) manage_extensions ;;
        7) manage_ipv6 ;;
        8) manage_certificates ;;
        9) update_remnawave_reverse ;;
        10) remove_script ;;
        0) echo -e "${COLOR_YELLOW}${LANG[EXIT]}${COLOR_RESET}"; exit 0 ;;
        *) echo -e "${COLOR_YELLOW}${LANG[INVALID_CHOICE]}${COLOR_RESET}"; sleep 1 ;;
    esac

    # После выполнения любой функции возвращаемся в меню (рекурсия или цикл)
    main_menu
}

# --- ТОЧКА ВХОДА ---

log_entry

if ! load_language; then
    show_language
    reading "Choose option (1-2):" LANG_OPTION
    case $LANG_OPTION in
        1) set_language en; echo "1" > "$LANG_FILE" ;;
        2) set_language ru; echo "2" > "$LANG_FILE" ;;
        *) error "Invalid choice. Please select 1-2." ;;
    esac
fi

check_root
check_os
install_script_if_missing

# Запуск главного меню
main_menu
